import { contact } from "./contact";

export interface Course {
  id: string;
  title: string;
  subtitle: string;
  category: "o-level" | "a-level" | "literature" | "creative-writing";
  categoryLabel: string;
  price: string;
  duration: string;
  schedule: string;
  description: string;
  featured: boolean;
  syllabus: string[];
  curriculum: {
    title: string;
    topics: string[];
  }[];
  outcomes: string[];
}

/** Public vault categories (marketing `/resources`). */
export type ResourceHubCategory =
  | "general-notes"
  | "topical-worksheets"
  | "yearly-past-papers"
  | "examiner-reports"
  | "checklists";

export interface Resource {
  id: string;
  title: string;
  category: ResourceHubCategory;
  subject: string;
  level: string;
  paper: string;
  year: string;
  /** Hosted PDF or document URL; replace with your CDN or `/public` paths. */
  fileUrl: string;
  description: string;
}

export const RESOURCE_HUB_CATEGORIES: {
  id: ResourceHubCategory;
  label: string;
  blurb: string;
}[] = [
  {
    id: "general-notes",
    label: "General Notes",
    blurb: "Syllabus maps, command words, and high-yield summaries.",
  },
  {
    id: "topical-worksheets",
    label: "Topical Worksheets",
    blurb: "Targeted drills aligned to common question types.",
  },
  {
    id: "yearly-past-papers",
    label: "Yearly Past Papers",
    blurb: "Timed papers and official mark schemes by session.",
  },
  {
    id: "examiner-reports",
    label: "Examiner Reports",
    blurb: "Principal examiner feedback and band-level insight.",
  },
  {
    id: "checklists",
    label: "Checklists",
    blurb: "Rubric-aligned self-review before you submit.",
  },
];

export const courses: Course[] = [
  {
    id: "o-level-english-1123",
    title: "O Level English Language",
    subtitle: "CAIE 1123 - Complete Preparation",
    category: "o-level",
    categoryLabel: "O Level",
    price: "PKR 25,000",
    duration: "4 Months",
    schedule: "3 sessions/week",
    description:
      "A structured, rubric-driven programme for Cambridge O Level English Language (1123). We build repeatable exam thinking through targeted practice on directed writing, composition, and comprehension.",
    featured: true,
    syllabus: [
      "Paper 1: Directed Writing & Composition",
      "Paper 2: Comprehension & Summary",
      "Examiner-aligned marking practice",
      "Timed mock examinations",
    ],
    curriculum: [
      {
        title: "Foundation: Reading & Analysis",
        topics: [
          "Comprehension strategies for unseen passages",
          "Inference and implication techniques",
          "Summary writing: precision under word limits",
          "Vocabulary building through context",
        ],
      },
      {
        title: "Directed Writing Mastery",
        topics: [
          "Understanding task requirements and audience",
          "Letter, report, speech, and article formats",
          "Tone adaptation and register control",
          "Examiner expectation alignment",
        ],
      },
      {
        title: "Composition & Creative Expression",
        topics: [
          "Narrative structure and pacing",
          "Descriptive writing: sensory detail and control",
          "Argumentative essay construction",
          "Discursive writing with balanced perspective",
        ],
      },
      {
        title: "Exam Strategy & Timed Practice",
        topics: [
          "Time allocation per question",
          "Common deduction patterns and how to avoid them",
          "Full paper mock under exam conditions",
          "Personalised feedback and improvement plans",
        ],
      },
    ],
    outcomes: [
      "Write with clarity and structure under timed conditions",
      "Identify and apply examiner marking criteria",
      "Produce directed writing that hits every assessment objective",
      "Develop a repeatable approach to comprehension and summary",
      "Build confidence through consistent, measurable progress",
    ],
  },
  {
    id: "a-level-english-9093",
    title: "AS/A Level English Language",
    subtitle: "CAIE 9093 - Advanced Programme",
    category: "a-level",
    categoryLabel: "A Level",
    price: "PKR 35,000",
    duration: "6 Months",
    schedule: "3 sessions/week",
    description:
      "An advanced programme for AS and A Level English Language (9093). We develop sophisticated analytical writing, commentary skills, and language awareness required for top-band performance.",
    featured: true,
    syllabus: [
      "Paper 1: Reading (Passages & Commentary)",
      "Paper 2: Writing (Directed & Composition)",
      "Paper 3: Text Analysis (A2)",
      "Paper 4: Language Topics (A2)",
    ],
    curriculum: [
      {
        title: "Textual Analysis & Commentary",
        topics: [
          "Linguistic framework for text analysis",
          "Audience, purpose, and context identification",
          "Stylistic feature recognition and effect analysis",
          "Commentary writing: structure and depth",
        ],
      },
      {
        title: "Advanced Directed Writing",
        topics: [
          "Complex audience adaptation",
          "Persuasive and rhetorical technique mastery",
          "Voice, register, and genre conventions",
          "Synthesis of source material into original writing",
        ],
      },
      {
        title: "Language in Context (A2)",
        topics: [
          "English as a global language: debates and perspectives",
          "Language and the self: identity and representation",
          "Language change: historical and contemporary",
          "Child language acquisition theories",
        ],
      },
      {
        title: "Examination Technique",
        topics: [
          "Band descriptor analysis for each paper",
          "Planning under pressure: structured approaches",
          "Full mock examinations with examiner-style feedback",
          "Targeted improvement based on diagnostic review",
        ],
      },
    ],
    outcomes: [
      "Analyse texts with precision using linguistic frameworks",
      "Write directed responses that demonstrate genre mastery",
      "Construct well-evidenced arguments on language topics",
      "Navigate A2 papers with confidence and critical depth",
      "Achieve top-band marks through deliberate, rubric-aligned practice",
    ],
  },
  {
    id: "english-literature",
    title: "English Literature",
    subtitle: "Poetry, Prose & Drama",
    category: "literature",
    categoryLabel: "Literature",
    price: "PKR 30,000",
    duration: "5 Months",
    schedule: "2 sessions/week",
    description:
      "Deep engagement with set texts, poetry, and drama. We develop critical reading, close analysis, and essay writing skills that go beyond surface-level interpretation.",
    featured: false,
    syllabus: [
      "Set text study: prose and drama",
      "Unseen poetry analysis",
      "Comparative essay techniques",
      "Contextual understanding and critical perspectives",
    ],
    curriculum: [
      {
        title: "Prose Study",
        topics: [
          "Character analysis and development",
          "Narrative voice and structural choices",
          "Thematic exploration across texts",
          "Contextual reading and critical lenses",
        ],
      },
      {
        title: "Drama Study",
        topics: [
          "Dramatic conventions and stagecraft",
          "Dialogue analysis and subtext",
          "Conflict, tension, and resolution",
          "Performance-aware close reading",
        ],
      },
      {
        title: "Poetry & Unseen Analysis",
        topics: [
          "Poetic form, metre, and sound",
          "Imagery, symbolism, and figurative language",
          "Unseen poetry: structured approach",
          "Comparative poetry essays",
        ],
      },
      {
        title: "Essay Craft",
        topics: [
          "Thesis development and argument structure",
          "Embedding quotations with analytical commentary",
          "Exam-style essay planning and execution",
          "Peer review and refinement",
        ],
      },
    ],
    outcomes: [
      "Produce sophisticated literary analysis essays",
      "Engage critically with set texts and unseen poetry",
      "Develop original interpretations supported by close reading",
      "Write with confidence under exam conditions",
      "Appreciate literature as a lens for understanding the world",
    ],
  },
  {
    id: "creative-writing-workshop",
    title: "Creative Writing Workshop",
    subtitle: "Voice, Craft & Expression",
    category: "creative-writing",
    categoryLabel: "Creative Writing",
    price: "PKR 15,000",
    duration: "6 Weeks",
    schedule: "1 session/week",
    description:
      "A focused workshop for students who want to strengthen their creative voice. Ideal for composition prep, personal statements, and developing writing as a lifelong skill.",
    featured: true,
    syllabus: [
      "Narrative and descriptive writing techniques",
      "Voice development and style",
      "Workshop-based peer feedback",
      "Portfolio development",
    ],
    curriculum: [
      {
        title: "Finding Your Voice",
        topics: [
          "Reading as a writer: analysing craft choices",
          "Point of view and narrative distance",
          "Developing a distinctive writing style",
          "Writing prompts and daily practice habits",
        ],
      },
      {
        title: "Craft & Technique",
        topics: [
          "Show, don't tell: sensory writing",
          "Dialogue that reveals character",
          "Pacing and structure in short fiction",
          "Editing and revision strategies",
        ],
      },
      {
        title: "Workshop & Portfolio",
        topics: [
          "Peer workshop sessions with guided feedback",
          "Responding to critique constructively",
          "Compiling a polished writing portfolio",
          "Connecting creative writing to exam composition",
        ],
      },
    ],
    outcomes: [
      "Develop a confident, distinctive writing voice",
      "Apply narrative and descriptive techniques with precision",
      "Give and receive constructive feedback effectively",
      "Build a portfolio of polished creative work",
      "Transfer creative skills to exam composition tasks",
    ],
  },
];

export const resources: Resource[] = [
  {
    id: "1123-s24-examiner-candidate-responses-p1",
    title: "May/June 2024 — examiner candidate responses (Paper 1)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-examiner-candidate-responses-p1.pdf",
    description: "Illustrative candidate responses with examiner commentary to calibrate expectations and banding.",
  },
  {
    id: "1123-s24-examiner-candidate-responses-p2",
    title: "May/June 2024 — examiner candidate responses (Paper 2)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-examiner-candidate-responses-p2.pdf",
    description: "Illustrative candidate responses with examiner commentary to calibrate expectations and banding.",
  },
  {
    id: "1123-s24-examiner-report",
    title: "O Level 1123 — principal examiner report (May/June 2024)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-examiner-report.pdf",
    description: "Official principal examiner report: themes, misconceptions, and what separated strong responses.",
  },
  {
    id: "1123-s24-insert-11",
    title: "May/June 2024 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-insert-11.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-s24-ms-11",
    title: "May/June 2024 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s24-ms-12",
    title: "May/June 2024 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s24-ms-21",
    title: "May/June 2024 — mark scheme (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "May/June 2024",
    fileUrl: "/resources/1123-s24-ms-21.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s25-examiner-report",
    title: "O Level 1123 — principal examiner report (May/June 2025)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-examiner-report.pdf",
    description: "Official principal examiner report: themes, misconceptions, and what separated strong responses.",
  },
  {
    id: "1123-s25-insert-11-alt",
    title: "May/June 2025 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-insert-11-alt.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-s25-insert-12",
    title: "May/June 2025 — Paper 2 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 insert",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-insert-12.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-s25-ms-11",
    title: "May/June 2025 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s25-ms-12",
    title: "May/June 2025 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-s25-qp-11",
    title: "May/June 2025 — question paper (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-qp-11.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-s25-qp-12",
    title: "May/June 2025 — question paper (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-qp-12.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-s25-qp-21",
    title: "May/June 2025 — question paper (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-qp-21.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-s25-qp-22",
    title: "May/June 2025 — question paper (Paper 2 (variant 22))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 22)",
    year: "May/June 2025",
    fileUrl: "/resources/1123-s25-qp-22.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-specimen-answers-paper-1",
    title: "Specimen — answers (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-answers-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-answers-paper-2",
    title: "Specimen — answers (Paper 2)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-answers-paper-2.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-examiner-candidate-responses-p1",
    title: "Specimen — examiner candidate responses (Paper 1)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-examiner-candidate-responses-p1.pdf",
    description: "Illustrative candidate responses with examiner commentary to calibrate expectations and banding.",
  },
  {
    id: "1123-specimen-examiner-candidate-responses-p2",
    title: "Specimen — examiner candidate responses (Paper 2)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-examiner-candidate-responses-p2.pdf",
    description: "Illustrative candidate responses with examiner commentary to calibrate expectations and banding.",
  },
  {
    id: "1123-specimen-insert-paper-1",
    title: "Specimen — insert (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-insert-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-ms-paper-1",
    title: "Specimen — mark scheme (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-ms-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-qp-paper-1",
    title: "Specimen — question paper (Paper 1)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-qp-paper-1.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-specimen-qp-paper-2",
    title: "Specimen — question paper (Paper 2)",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Specimen",
    fileUrl: "/resources/1123-specimen-qp-paper-2.pdf",
    description: "Cambridge specimen materials for examination from 2024.",
  },
  {
    id: "1123-w24-examiner-report",
    title: "O Level 1123 — principal examiner report (Nov 2024)",
    category: "examiner-reports",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-examiner-report.pdf",
    description: "Official principal examiner report: themes, misconceptions, and what separated strong responses.",
  },
  {
    id: "1123-w24-insert-11",
    title: "Nov 2024 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-insert-11.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w24-insert-12",
    title: "Nov 2024 — Paper 2 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 insert",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-insert-12.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w24-ms-11",
    title: "Nov 2024 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w24-ms-12",
    title: "Nov 2024 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w24-qp-11",
    title: "Nov 2024 — question paper (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-qp-11.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w24-qp-12",
    title: "Nov 2024 — question paper (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-qp-12.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w24-qp-21",
    title: "Nov 2024 — question paper (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-qp-21.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w24-qp-22",
    title: "Nov 2024 — question paper (Paper 2 (variant 22))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 22)",
    year: "Nov 2024",
    fileUrl: "/resources/1123-w24-qp-22.pdf",
    description: "Official past question paper for timed practice and pacing.",
  },
  {
    id: "1123-w25-insert-11",
    title: "Nov 2025 — Paper 1 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 insert",
    year: "Nov 2025",
    fileUrl: "/resources/1123-w25-insert-11.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w25-insert-12",
    title: "Nov 2025 — Paper 2 insert",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 insert",
    year: "Nov 2025",
    fileUrl: "/resources/1123-w25-insert-12.pdf",
    description: "Official insert booklet paired with the matching question paper.",
  },
  {
    id: "1123-w25-ms-11",
    title: "Nov 2025 — mark scheme (Paper 1 (variant 11))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 11)",
    year: "Nov 2025",
    fileUrl: "/resources/1123-w25-ms-11.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w25-ms-12",
    title: "Nov 2025 — mark scheme (Paper 1 (variant 12))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1 (variant 12)",
    year: "Nov 2025",
    fileUrl: "/resources/1123-w25-ms-12.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "1123-w25-ms-21",
    title: "Nov 2025 — mark scheme (Paper 2 (variant 21))",
    category: "yearly-past-papers",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2 (variant 21)",
    year: "Nov 2025",
    fileUrl: "/resources/1123-w25-ms-21.pdf",
    description: "Official mark scheme for accurate self-marking and gap analysis.",
  },
  {
    id: "changes-in-the-syllabus-1123",
    title: "Syllabus changes — 1123 overview",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/changes-in-the-syllabus-1123.pdf",
    description: "What changed in the latest syllabus cycle and how it affects classroom prep.",
  },
  {
    id: "complete-vocabulary-list-1123",
    title: "Complete vocabulary list (1123)",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/complete-vocabulary-list-1123.pdf",
    description: "A wide-ranging vocabulary bank to support precision and range in writing tasks.",
  },
  {
    id: "o-level-1123-syllabus",
    title: "O Level English 1123 — syllabus (full)",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/o-level-1123-syllabus.pdf",
    description: "CAIE syllabus document: aims, content, and assessment objectives.",
  },
  {
    id: "olevel-directed-writing-all-formats-notes",
    title: "Directed writing — all formats (notes)",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/olevel-directed-writing-all-formats-notes.pdf",
    description: "Layouts and moves for common directed writing formats on Paper 1.",
  },
  {
    id: "olevel-directed-writing-formats-1123-notes",
    title: "Directed writing formats — 1123",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/olevel-directed-writing-formats-1123-notes.pdf",
    description: "Format expectations and structure reminders aligned to examiner criteria.",
  },
  {
    id: "olevel-directed-writing-text-wise-evaluation-notes",
    title: "Directed writing — text-wise evaluation",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Current",
    fileUrl: "/resources/olevel-directed-writing-text-wise-evaluation-notes.pdf",
    description: "How to evaluate prompts closely and shape a task-sharp response.",
  },
  {
    id: "syllabus-1123-specification",
    title: "1123 specification — compact reference",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/syllabus-1123-specification.pdf",
    description: "A tighter syllabus reference for quick orientation before mocks.",
  },
  {
    id: "vocabulary-companion-1123",
    title: "Vocabulary companion pack",
    category: "general-notes",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Current",
    fileUrl: "/resources/vocabulary-companion-1123.pdf",
    description: "Curated vocabulary support for O Level English responses.",
  },
  {
    id: "worksheet-26-march-vocab-test-ms-marking-scheme",
    title: "Vocabulary marking scheme — test ",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-26-march-vocab-test-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-exam-hack-4",
    title: "Exam hack — set 4",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Practice",
    fileUrl: "/resources/worksheet-exam-hack-4.pdf",
    description: "Short drill pack for reading and writing exam technique.",
  },
  {
    id: "worksheet-exam-hack-writers-effect",
    title: "Exam hack — writer\'s effect",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 2",
    year: "Practice",
    fileUrl: "/resources/worksheet-exam-hack-writers-effect.pdf",
    description: "Targeted practice on identifying and explaining writer’s effect.",
  },
  {
    id: "worksheet-interviewer-question-practice",
    title: "Interviewer question practice set",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-interviewer-question-practice.pdf",
    description: "Practice responding to interviewer-style prompts with clarity and control.",
  },
  {
    id: "worksheet-phrases-to-utilize",
    title: "Phrases to utilise",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-phrases-to-utilize.pdf",
    description: "High-utility phrases you can adapt across directed tasks.",
  },
  {
    id: "worksheet-pop-quiz",
    title: "Pop quiz — quick recall",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-pop-quiz.pdf",
    description: "Rapid checks to surface gaps before you attempt full papers.",
  },
  {
    id: "worksheet-sentences-you-can-use",
    title: "Sentences you can use",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-sentences-you-can-use.pdf",
    description: "Sentence patterns to improve cohesion, tone, and control.",
  },
  {
    id: "worksheet-tip-of-the-day-01",
    title: "Tip of the day — card 01",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-01.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-02",
    title: "Tip of the day — card 02",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-02.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-03",
    title: "Tip of the day — card 03",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-03.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-04",
    title: "Tip of the day — card 04",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-04.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-05",
    title: "Tip of the day — card 05",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-05.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-tip-of-the-day-06",
    title: "Tip of the day — card 06",
    category: "checklists",
    subject: "English Language 1123",
    level: "O Level",
    paper: "All papers",
    year: "Practice",
    fileUrl: "/resources/worksheet-tip-of-the-day-06.pdf",
    description: "A bite-sized reminder you can use as a pre-writing or pre-exam checklist.",
  },
  {
    id: "worksheet-vocab-test-1-qp",
    title: "Vocabulary question paper — test 1",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-1-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-10-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 10",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-10-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-10-qp",
    title: "Vocabulary question paper — test 10",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-10-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-10-ws",
    title: "Vocabulary worksheet — test 10",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-10-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-11-qp",
    title: "Vocabulary question paper — test 11",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-11-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-11-ws",
    title: "Vocabulary worksheet — test 11",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-11-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-12-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 12",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-12-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-12-qp",
    title: "Vocabulary question paper — test 12",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-12-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-12-ws",
    title: "Vocabulary worksheet — test 12",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-12-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-13-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 13",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-13-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-13-qp",
    title: "Vocabulary question paper — test 13",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-13-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-13-ws",
    title: "Vocabulary worksheet — test 13",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-13-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-14-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 14",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-14-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-14-qp",
    title: "Vocabulary question paper — test 14",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-14-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-14-ws",
    title: "Vocabulary worksheet — test 14",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-14-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-2-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 2",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-2-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-3-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 3",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-3-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-3-qp",
    title: "Vocabulary question paper — test 3",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-3-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-4-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 4",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-4-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-4-qp",
    title: "Vocabulary question paper — test 4",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-4-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-4-ws",
    title: "Vocabulary worksheet — test 4",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-4-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-5-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 5",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-5-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-5-qp",
    title: "Vocabulary question paper — test 5",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-5-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-5-ws",
    title: "Vocabulary worksheet — test 5",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-5-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-6-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 6",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-6-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-6-qp",
    title: "Vocabulary question paper — test 6",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-6-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-6-ws",
    title: "Vocabulary worksheet — test 6",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-6-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-7-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 7",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-7-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-7-qp",
    title: "Vocabulary question paper — test 7",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-7-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-7-ws",
    title: "Vocabulary worksheet — test 7",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-7-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-8-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 8",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-8-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-8-qp",
    title: "Vocabulary question paper — test 8",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-8-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-8-ws",
    title: "Vocabulary worksheet — test 8",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-8-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocab-test-9-ms-marking-scheme",
    title: "Vocabulary marking scheme — test 9",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-9-ms-marking-scheme.pdf",
    description: "Marking scheme for the matching vocabulary test.",
  },
  {
    id: "worksheet-vocab-test-9-qp",
    title: "Vocabulary question paper — test 9",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-9-qp.pdf",
    description: "Timed-light recall and usage check for active vocabulary.",
  },
  {
    id: "worksheet-vocab-test-9-ws",
    title: "Vocabulary worksheet — test 9",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Vocabulary",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocab-test-9-ws.pdf",
    description: "Apply and consolidate vocabulary in short exam-style tasks.",
  },
  {
    id: "worksheet-vocabulary-bank-2",
    title: "Vocabulary bank — set 2",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-vocabulary-bank-2.pdf",
    description: "Additional vocabulary prompts for breadth and precision.",
  },
  {
    id: "worksheet-writing-vocab-ms-marking-scheme",
    title: "Writing vocabulary — marking scheme",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-writing-vocab-ms-marking-scheme.pdf",
    description: "Marking scheme for the writing vocabulary question paper.",
  },
  {
    id: "worksheet-writing-vocab-qp",
    title: "Writing vocabulary — question paper",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-writing-vocab-qp.pdf",
    description: "Writing-focused vocabulary questions for Paper 1 preparation.",
  },
  {
    id: "worksheet-writing-words-day-15",
    title: "Writing words — day 15",
    category: "topical-worksheets",
    subject: "English Language 1123",
    level: "O Level",
    paper: "Paper 1",
    year: "Practice",
    fileUrl: "/resources/worksheet-writing-words-day-15.pdf",
    description: "Day-style vocabulary push for consistent writing improvement.",
  },
];

export const siteConfig = {
  name: "Jaweria Amer",
  title: "Jaweria Amer - O/A Level English Specialist",
  description:
    "Rubric-driven Cambridge O/A Level English tutoring in Karachi. Structured practice, precise feedback, and mentorship that builds independent thinkers.",
  tagline: "Master CAIE English with Clarity and Care",
  whatsappNumber: contact.whatsapp,
  whatsappMessage: contact.messageDefault,
  stats: [
    { value: "95%", label: "Students scored A*/A" },
    { value: "500+", label: "Students mentored" },
    { value: "8+", label: "Years of experience" },
    { value: "12", label: "CAIE exam sessions" },
  ],
  roadmap: [
    {
      step: 1,
      title: "Diagnostic Review",
      description: "We assess your current level, identify patterns, and pinpoint exactly what needs attention.",
    },
    {
      step: 2,
      title: "Structured Plan",
      description: "A clear, week-by-week plan aligned to your exam timeline and personal goals.",
    },
    {
      step: 3,
      title: "Targeted Practice",
      description: "Rubric-driven exercises, timed papers, and focused skill-building sessions.",
    },
    {
      step: 4,
      title: "Feedback & Refinement",
      description: "Detailed, examiner-style feedback on every piece of work. We fix what matters most.",
    },
    {
      step: 5,
      title: "Exam Readiness",
      description: "Full mock papers under real conditions. You walk into the exam hall prepared and confident.",
    },
  ],
  navigation: [
    { label: "Home", href: "/" },
    { label: "Courses", href: "/courses" },
    { label: "Resources", href: "/resources" },
    { label: "About", href: "/about" },
  ],
};
